// Code generated by ent, DO NOT EDIT.

package comments

import (
	"server04/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Comments {
	return predicate.Comments(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Comments {
	return predicate.Comments(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Comments {
	return predicate.Comments(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Comments {
	return predicate.Comments(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Comments {
	return predicate.Comments(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Comments {
	return predicate.Comments(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Comments {
	return predicate.Comments(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Comments {
	return predicate.Comments(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Comments {
	return predicate.Comments(sql.FieldLTE(FieldID, id))
}

// HasVideoId applies the HasEdge predicate on the "videoId" edge.
func HasVideoId() predicate.Comments {
	return predicate.Comments(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, VideoIdTable, VideoIdPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVideoIdWith applies the HasEdge predicate on the "videoId" edge with a given conditions (other predicates).
func HasVideoIdWith(preds ...predicate.Videos) predicate.Comments {
	return predicate.Comments(func(s *sql.Selector) {
		step := newVideoIdStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserId applies the HasEdge predicate on the "userId" edge.
func HasUserId() predicate.Comments {
	return predicate.Comments(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UserIdTable, UserIdPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserIdWith applies the HasEdge predicate on the "userId" edge with a given conditions (other predicates).
func HasUserIdWith(preds ...predicate.UserSec) predicate.Comments {
	return predicate.Comments(func(s *sql.Selector) {
		step := newUserIdStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Comments) predicate.Comments {
	return predicate.Comments(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Comments) predicate.Comments {
	return predicate.Comments(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Comments) predicate.Comments {
	return predicate.Comments(sql.NotPredicates(p))
}
