// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server04/ent/comments"
	"server04/ent/usersec"
	"server04/ent/videos"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentsCreate is the builder for creating a Comments entity.
type CommentsCreate struct {
	config
	mutation *CommentsMutation
	hooks    []Hook
}

// SetCommentStr sets the "commentStr" field.
func (cc *CommentsCreate) SetCommentStr(s string) *CommentsCreate {
	cc.mutation.SetCommentStr(s)
	return cc
}

// AddVideoIdIDs adds the "videoId" edge to the Videos entity by IDs.
func (cc *CommentsCreate) AddVideoIdIDs(ids ...int) *CommentsCreate {
	cc.mutation.AddVideoIdIDs(ids...)
	return cc
}

// AddVideoId adds the "videoId" edges to the Videos entity.
func (cc *CommentsCreate) AddVideoId(v ...*Videos) *CommentsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return cc.AddVideoIdIDs(ids...)
}

// AddUserIdIDs adds the "userId" edge to the UserSec entity by IDs.
func (cc *CommentsCreate) AddUserIdIDs(ids ...int) *CommentsCreate {
	cc.mutation.AddUserIdIDs(ids...)
	return cc
}

// AddUserId adds the "userId" edges to the UserSec entity.
func (cc *CommentsCreate) AddUserId(u ...*UserSec) *CommentsCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cc.AddUserIdIDs(ids...)
}

// Mutation returns the CommentsMutation object of the builder.
func (cc *CommentsCreate) Mutation() *CommentsMutation {
	return cc.mutation
}

// Save creates the Comments in the database.
func (cc *CommentsCreate) Save(ctx context.Context) (*Comments, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommentsCreate) SaveX(ctx context.Context) *Comments {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommentsCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommentsCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommentsCreate) check() error {
	if _, ok := cc.mutation.CommentStr(); !ok {
		return &ValidationError{Name: "commentStr", err: errors.New(`ent: missing required field "Comments.commentStr"`)}
	}
	return nil
}

func (cc *CommentsCreate) sqlSave(ctx context.Context) (*Comments, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CommentsCreate) createSpec() (*Comments, *sqlgraph.CreateSpec) {
	var (
		_node = &Comments{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(comments.Table, sqlgraph.NewFieldSpec(comments.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.CommentStr(); ok {
		_spec.SetField(comments.FieldCommentStr, field.TypeString, value)
		_node.CommentStr = value
	}
	if nodes := cc.mutation.VideoIdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   comments.VideoIdTable,
			Columns: comments.VideoIdPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(videos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.UserIdIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   comments.UserIdTable,
			Columns: comments.UserIdPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersec.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommentsCreateBulk is the builder for creating many Comments entities in bulk.
type CommentsCreateBulk struct {
	config
	err      error
	builders []*CommentsCreate
}

// Save creates the Comments entities in the database.
func (ccb *CommentsCreateBulk) Save(ctx context.Context) ([]*Comments, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Comments, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommentsCreateBulk) SaveX(ctx context.Context) []*Comments {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommentsCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommentsCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
