// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"server04/ent/comments"
	"server04/ent/likes"
	"server04/ent/predicate"
	"server04/ent/userprofile"
	"server04/ent/usersec"
	"server04/ent/videos"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSecQuery is the builder for querying UserSec entities.
type UserSecQuery struct {
	config
	ctx           *QueryContext
	order         []usersec.OrderOption
	inters        []Interceptor
	predicates    []predicate.UserSec
	withProfile   *UserProfileQuery
	withVideoId   *VideosQuery
	withCommentId *CommentsQuery
	withLikeId    *LikesQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserSecQuery builder.
func (usq *UserSecQuery) Where(ps ...predicate.UserSec) *UserSecQuery {
	usq.predicates = append(usq.predicates, ps...)
	return usq
}

// Limit the number of records to be returned by this query.
func (usq *UserSecQuery) Limit(limit int) *UserSecQuery {
	usq.ctx.Limit = &limit
	return usq
}

// Offset to start from.
func (usq *UserSecQuery) Offset(offset int) *UserSecQuery {
	usq.ctx.Offset = &offset
	return usq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (usq *UserSecQuery) Unique(unique bool) *UserSecQuery {
	usq.ctx.Unique = &unique
	return usq
}

// Order specifies how the records should be ordered.
func (usq *UserSecQuery) Order(o ...usersec.OrderOption) *UserSecQuery {
	usq.order = append(usq.order, o...)
	return usq
}

// QueryProfile chains the current query on the "profile" edge.
func (usq *UserSecQuery) QueryProfile() *UserProfileQuery {
	query := (&UserProfileClient{config: usq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := usq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersec.Table, usersec.FieldID, selector),
			sqlgraph.To(userprofile.Table, userprofile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usersec.ProfileTable, usersec.ProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(usq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVideoId chains the current query on the "videoId" edge.
func (usq *UserSecQuery) QueryVideoId() *VideosQuery {
	query := (&VideosClient{config: usq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := usq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersec.Table, usersec.FieldID, selector),
			sqlgraph.To(videos.Table, videos.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, usersec.VideoIdTable, usersec.VideoIdColumn),
		)
		fromU = sqlgraph.SetNeighbors(usq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommentId chains the current query on the "commentId" edge.
func (usq *UserSecQuery) QueryCommentId() *CommentsQuery {
	query := (&CommentsClient{config: usq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := usq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersec.Table, usersec.FieldID, selector),
			sqlgraph.To(comments.Table, comments.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, usersec.CommentIdTable, usersec.CommentIdPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(usq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLikeId chains the current query on the "likeId" edge.
func (usq *UserSecQuery) QueryLikeId() *LikesQuery {
	query := (&LikesClient{config: usq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := usq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersec.Table, usersec.FieldID, selector),
			sqlgraph.To(likes.Table, likes.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, usersec.LikeIdTable, usersec.LikeIdPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(usq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserSec entity from the query.
// Returns a *NotFoundError when no UserSec was found.
func (usq *UserSecQuery) First(ctx context.Context) (*UserSec, error) {
	nodes, err := usq.Limit(1).All(setContextOp(ctx, usq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersec.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (usq *UserSecQuery) FirstX(ctx context.Context) *UserSec {
	node, err := usq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserSec ID from the query.
// Returns a *NotFoundError when no UserSec ID was found.
func (usq *UserSecQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = usq.Limit(1).IDs(setContextOp(ctx, usq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersec.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (usq *UserSecQuery) FirstIDX(ctx context.Context) int {
	id, err := usq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserSec entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserSec entity is found.
// Returns a *NotFoundError when no UserSec entities are found.
func (usq *UserSecQuery) Only(ctx context.Context) (*UserSec, error) {
	nodes, err := usq.Limit(2).All(setContextOp(ctx, usq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersec.Label}
	default:
		return nil, &NotSingularError{usersec.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (usq *UserSecQuery) OnlyX(ctx context.Context) *UserSec {
	node, err := usq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserSec ID in the query.
// Returns a *NotSingularError when more than one UserSec ID is found.
// Returns a *NotFoundError when no entities are found.
func (usq *UserSecQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = usq.Limit(2).IDs(setContextOp(ctx, usq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersec.Label}
	default:
		err = &NotSingularError{usersec.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (usq *UserSecQuery) OnlyIDX(ctx context.Context) int {
	id, err := usq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserSecs.
func (usq *UserSecQuery) All(ctx context.Context) ([]*UserSec, error) {
	ctx = setContextOp(ctx, usq.ctx, "All")
	if err := usq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserSec, *UserSecQuery]()
	return withInterceptors[[]*UserSec](ctx, usq, qr, usq.inters)
}

// AllX is like All, but panics if an error occurs.
func (usq *UserSecQuery) AllX(ctx context.Context) []*UserSec {
	nodes, err := usq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserSec IDs.
func (usq *UserSecQuery) IDs(ctx context.Context) (ids []int, err error) {
	if usq.ctx.Unique == nil && usq.path != nil {
		usq.Unique(true)
	}
	ctx = setContextOp(ctx, usq.ctx, "IDs")
	if err = usq.Select(usersec.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (usq *UserSecQuery) IDsX(ctx context.Context) []int {
	ids, err := usq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (usq *UserSecQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, usq.ctx, "Count")
	if err := usq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, usq, querierCount[*UserSecQuery](), usq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (usq *UserSecQuery) CountX(ctx context.Context) int {
	count, err := usq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (usq *UserSecQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, usq.ctx, "Exist")
	switch _, err := usq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (usq *UserSecQuery) ExistX(ctx context.Context) bool {
	exist, err := usq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserSecQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (usq *UserSecQuery) Clone() *UserSecQuery {
	if usq == nil {
		return nil
	}
	return &UserSecQuery{
		config:        usq.config,
		ctx:           usq.ctx.Clone(),
		order:         append([]usersec.OrderOption{}, usq.order...),
		inters:        append([]Interceptor{}, usq.inters...),
		predicates:    append([]predicate.UserSec{}, usq.predicates...),
		withProfile:   usq.withProfile.Clone(),
		withVideoId:   usq.withVideoId.Clone(),
		withCommentId: usq.withCommentId.Clone(),
		withLikeId:    usq.withLikeId.Clone(),
		// clone intermediate query.
		sql:  usq.sql.Clone(),
		path: usq.path,
	}
}

// WithProfile tells the query-builder to eager-load the nodes that are connected to
// the "profile" edge. The optional arguments are used to configure the query builder of the edge.
func (usq *UserSecQuery) WithProfile(opts ...func(*UserProfileQuery)) *UserSecQuery {
	query := (&UserProfileClient{config: usq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	usq.withProfile = query
	return usq
}

// WithVideoId tells the query-builder to eager-load the nodes that are connected to
// the "videoId" edge. The optional arguments are used to configure the query builder of the edge.
func (usq *UserSecQuery) WithVideoId(opts ...func(*VideosQuery)) *UserSecQuery {
	query := (&VideosClient{config: usq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	usq.withVideoId = query
	return usq
}

// WithCommentId tells the query-builder to eager-load the nodes that are connected to
// the "commentId" edge. The optional arguments are used to configure the query builder of the edge.
func (usq *UserSecQuery) WithCommentId(opts ...func(*CommentsQuery)) *UserSecQuery {
	query := (&CommentsClient{config: usq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	usq.withCommentId = query
	return usq
}

// WithLikeId tells the query-builder to eager-load the nodes that are connected to
// the "likeId" edge. The optional arguments are used to configure the query builder of the edge.
func (usq *UserSecQuery) WithLikeId(opts ...func(*LikesQuery)) *UserSecQuery {
	query := (&LikesClient{config: usq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	usq.withLikeId = query
	return usq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Password string `json:"password,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserSec.Query().
//		GroupBy(usersec.FieldPassword).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (usq *UserSecQuery) GroupBy(field string, fields ...string) *UserSecGroupBy {
	usq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserSecGroupBy{build: usq}
	grbuild.flds = &usq.ctx.Fields
	grbuild.label = usersec.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Password string `json:"password,omitempty"`
//	}
//
//	client.UserSec.Query().
//		Select(usersec.FieldPassword).
//		Scan(ctx, &v)
func (usq *UserSecQuery) Select(fields ...string) *UserSecSelect {
	usq.ctx.Fields = append(usq.ctx.Fields, fields...)
	sbuild := &UserSecSelect{UserSecQuery: usq}
	sbuild.label = usersec.Label
	sbuild.flds, sbuild.scan = &usq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserSecSelect configured with the given aggregations.
func (usq *UserSecQuery) Aggregate(fns ...AggregateFunc) *UserSecSelect {
	return usq.Select().Aggregate(fns...)
}

func (usq *UserSecQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range usq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, usq); err != nil {
				return err
			}
		}
	}
	for _, f := range usq.ctx.Fields {
		if !usersec.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if usq.path != nil {
		prev, err := usq.path(ctx)
		if err != nil {
			return err
		}
		usq.sql = prev
	}
	return nil
}

func (usq *UserSecQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserSec, error) {
	var (
		nodes       = []*UserSec{}
		withFKs     = usq.withFKs
		_spec       = usq.querySpec()
		loadedTypes = [4]bool{
			usq.withProfile != nil,
			usq.withVideoId != nil,
			usq.withCommentId != nil,
			usq.withLikeId != nil,
		}
	)
	if usq.withProfile != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, usersec.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserSec).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserSec{config: usq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, usq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := usq.withProfile; query != nil {
		if err := usq.loadProfile(ctx, query, nodes, nil,
			func(n *UserSec, e *UserProfile) { n.Edges.Profile = e }); err != nil {
			return nil, err
		}
	}
	if query := usq.withVideoId; query != nil {
		if err := usq.loadVideoId(ctx, query, nodes,
			func(n *UserSec) { n.Edges.VideoId = []*Videos{} },
			func(n *UserSec, e *Videos) { n.Edges.VideoId = append(n.Edges.VideoId, e) }); err != nil {
			return nil, err
		}
	}
	if query := usq.withCommentId; query != nil {
		if err := usq.loadCommentId(ctx, query, nodes,
			func(n *UserSec) { n.Edges.CommentId = []*Comments{} },
			func(n *UserSec, e *Comments) { n.Edges.CommentId = append(n.Edges.CommentId, e) }); err != nil {
			return nil, err
		}
	}
	if query := usq.withLikeId; query != nil {
		if err := usq.loadLikeId(ctx, query, nodes,
			func(n *UserSec) { n.Edges.LikeId = []*Likes{} },
			func(n *UserSec, e *Likes) { n.Edges.LikeId = append(n.Edges.LikeId, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (usq *UserSecQuery) loadProfile(ctx context.Context, query *UserProfileQuery, nodes []*UserSec, init func(*UserSec), assign func(*UserSec, *UserProfile)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserSec)
	for i := range nodes {
		if nodes[i].user_profile_user_secure == nil {
			continue
		}
		fk := *nodes[i].user_profile_user_secure
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(userprofile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_profile_user_secure" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (usq *UserSecQuery) loadVideoId(ctx context.Context, query *VideosQuery, nodes []*UserSec, init func(*UserSec), assign func(*UserSec, *Videos)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*UserSec)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Videos(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(usersec.VideoIdColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_sec_video_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_sec_video_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_sec_video_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (usq *UserSecQuery) loadCommentId(ctx context.Context, query *CommentsQuery, nodes []*UserSec, init func(*UserSec), assign func(*UserSec, *Comments)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*UserSec)
	nids := make(map[int]map[*UserSec]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(usersec.CommentIdTable)
		s.Join(joinT).On(s.C(comments.FieldID), joinT.C(usersec.CommentIdPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(usersec.CommentIdPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(usersec.CommentIdPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*UserSec]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Comments](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "commentId" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (usq *UserSecQuery) loadLikeId(ctx context.Context, query *LikesQuery, nodes []*UserSec, init func(*UserSec), assign func(*UserSec, *Likes)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*UserSec)
	nids := make(map[int]map[*UserSec]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(usersec.LikeIdTable)
		s.Join(joinT).On(s.C(likes.FieldID), joinT.C(usersec.LikeIdPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(usersec.LikeIdPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(usersec.LikeIdPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*UserSec]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Likes](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "likeId" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (usq *UserSecQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := usq.querySpec()
	_spec.Node.Columns = usq.ctx.Fields
	if len(usq.ctx.Fields) > 0 {
		_spec.Unique = usq.ctx.Unique != nil && *usq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, usq.driver, _spec)
}

func (usq *UserSecQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usersec.Table, usersec.Columns, sqlgraph.NewFieldSpec(usersec.FieldID, field.TypeInt))
	_spec.From = usq.sql
	if unique := usq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if usq.path != nil {
		_spec.Unique = true
	}
	if fields := usq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersec.FieldID)
		for i := range fields {
			if fields[i] != usersec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := usq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := usq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := usq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := usq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (usq *UserSecQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(usq.driver.Dialect())
	t1 := builder.Table(usersec.Table)
	columns := usq.ctx.Fields
	if len(columns) == 0 {
		columns = usersec.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if usq.sql != nil {
		selector = usq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if usq.ctx.Unique != nil && *usq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range usq.predicates {
		p(selector)
	}
	for _, p := range usq.order {
		p(selector)
	}
	if offset := usq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := usq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserSecGroupBy is the group-by builder for UserSec entities.
type UserSecGroupBy struct {
	selector
	build *UserSecQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (usgb *UserSecGroupBy) Aggregate(fns ...AggregateFunc) *UserSecGroupBy {
	usgb.fns = append(usgb.fns, fns...)
	return usgb
}

// Scan applies the selector query and scans the result into the given value.
func (usgb *UserSecGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, usgb.build.ctx, "GroupBy")
	if err := usgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserSecQuery, *UserSecGroupBy](ctx, usgb.build, usgb, usgb.build.inters, v)
}

func (usgb *UserSecGroupBy) sqlScan(ctx context.Context, root *UserSecQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(usgb.fns))
	for _, fn := range usgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*usgb.flds)+len(usgb.fns))
		for _, f := range *usgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*usgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserSecSelect is the builder for selecting fields of UserSec entities.
type UserSecSelect struct {
	*UserSecQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uss *UserSecSelect) Aggregate(fns ...AggregateFunc) *UserSecSelect {
	uss.fns = append(uss.fns, fns...)
	return uss
}

// Scan applies the selector query and scans the result into the given value.
func (uss *UserSecSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uss.ctx, "Select")
	if err := uss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserSecQuery, *UserSecSelect](ctx, uss.UserSecQuery, uss, uss.inters, v)
}

func (uss *UserSecSelect) sqlScan(ctx context.Context, root *UserSecQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uss.fns))
	for _, fn := range uss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
